name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Check for outdated dependencies
      run: npm run check-updates
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build